### ISSUE TITLE
Renaming a darknode name doesn´t get implemented properly

### ISSUE THREAD

**Issue by devoger** [republicprotocol/darknode-cli#15]
My darknode name is node1 and later I decided to change it to powernode1.
In the darknode command center it looks correct and showing my newly renamed node.

However when I withdraw my eth through terminal and run this:
darknode withdraw powernode1 --address myaddress

I get this error:
node with the name doesn't exist

By checking my node list, I realize it is still using the original darknode name which was node1.
It should use my new defined name... otherwise I have to remember the first darknode I used when I first register. Its fine for the techy people but not very user friendly for the average Joe.

**Comment by tok-kkk** [comment]
Thank @devoger for reporting this. The command centre only stores the name in the browser (it shows this if you hover on the edit button in your command centre). The CLI reads names from files, so it won't be able to know the change you make in browser. 
We're working on supporting renaming darknode in the CLI and hopefully that will fix your issue.
