### ISSUE TITLE
Offering help for Google Cloud integration

### ISSUE THREAD

**Issue by Pega88** [republicprotocol/darknode-cli#25]
At the moment the CLI only allows deployments on AWS and DO. As a Google Cloud expert, I'm offering my assistance in integration with GCP. I could not find a branch nor PR relating to GCP deployment of the darknode, so not sure at what stage that development is, since it says "coming soon".

**Comment by loongy** [comment]
@Pega88 we have not begun support for GCP yet. We will gladly review and merge a PR for any full/partial set of features that will move towards support for GCP.

**Comment by Pega88** [comment]
ok, good to hear nothing has started. That way I'm not doing double work. Will give it a shot when I get back from holidays.

**Comment by Pega88** [comment]
@loongy could there be a private repo (https://github.com/republicprotocol/ren-go) that is required to setup the project?

```
 ~/go/bin/src/github.com/republicprotocol/darknode-cli> dep ensure
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/republicprotocol/ren-go: 
	(1) failed to list versions for https://github.com/republicprotocol/ren-go: remote: Repository not found.
fatal: repository 'https://github.com/republicprotocol/ren-go/' not found
: exit status 128
	(2) failed to list versions for ssh://git@github.com/republicprotocol/ren-go: ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
	(3) failed to list versions for git://github.com/republicprotocol/ren-go: fatal: remote error: 
  Repository not found.
: exit status 128
	(4) failed to list versions for http://github.com/republicprotocol/ren-go: remote: Repository not found.
fatal: repository 'https://github.com/republicprotocol/ren-go/' not found
: exit status 128

```

**Comment by tok-kkk** [comment]
Sorry @Pega88. That's an old repo. I'll fix up the dependencies this week so you can start.

**Comment by Pega88** [comment]
thanks @tok-kkk -  I also see some optimizations that I'd like to propose, mainly creating an interface for the different cloud vendors so others can easily be added. I guess that for that anyway I need #24 to be merged. Looking forward to start contributing!

**Comment by Pega88** [comment]
@tok-kkk I've come this far as that I've created a terraform config that deploys a VM on Google Cloud, sets firewall etc and runs the init.sh and install.sh scripts. I manually used a darknode-config.json that was generated by the darknode-cli tool for AWS, just to have something working (don't fully understand this config yet).

My goal is to just have a node semi-manual set up to understand the whole process instead of blindly copying AWS to GCP. So I'm at this point now that the service seems to have correctly started, since it seems to have found 169 peers:

<img width="1007" alt="Screenshot 2019-08-12 at 17 21 13" src="https://user-images.githubusercontent.com/1451524/62877684-df587000-bd27-11e9-841e-9f6029a03947.png">

however I'm not sure if I should be able to access a UI on the VM's public IP now? Or would only gRPC connections on port 18514 give anything? Just wanna make sure the node is fully functional and what better than a nice UI showing up :).

**Comment by tok-kkk** [comment]
@Pega88 There is a UI but unfortunately it is only used for registering and deregistering Darknodes. We'll have a way to view the status in the next version of Darknode Command Centre. According to the logs, the Darknode is functioning well. I've also fixed the dependency issue on the `develop` branch, so you should be able to `dep ensure`.
Let me know if you have any other issues and thanks again for offering help!

**Comment by Pega88** [comment]
@tok-kkk I've been working on this part but now I'm stuck at running even the basic building and running it from code on AWS for example. It's looking for `/Users/pega88/.darknode/instance/aws/aws.tmpl` but of course that's not in there, because that's downloaded and copied over there from the install.sh script.

When you are building and running locally, are you manually populating those files? I'm not sure why those files are not just referenced as a resource in the executable, instead of hardcoded-located over there?
Or are you using any specific practice for local building that I'm missing?

I manually made the ~/.darknode/bin and ~/.darknode/darknodes directories since the install.sh shell script does that as well, but the utils.go is referencing ~/.darknode (line 19) as where it wants the aws.tmpl file to be. Simply put, I expect to be able to have everything working from source with a simple `go run .` in the cmd folder.

Thnx for any feedback!

Thnx

**Comment by Pega88** [comment]
Closing as per #30 - fully integrated. I'll open another one for local building, it should not have to rely on manually provisioning the terraform templates in ~/.darknode IMHO.
