### ISSUE TITLE
422 Region is not available

### ISSUE THREAD

**Issue by TheDon22** [republicprotocol/darknode-cli#5]
after running "deploying darknode" command
`darknode up --network testnet --name my-first-darknode --do --do-token YOUR-API-TOKEN`

got error message 
"digitalocean_droplet.darknode: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 Region is not available"

solved it by running the next command on the user guide, selecting the region.

using digital ocean with macOSX

**Comment by tok-kkk** [comment]
Thanks @TheDon22 for reporting the issue. Currently, the CLI randomly picks a region when the region flag is not specified. For digital ocean, not all regions are available to all users.  This will be fixed it in the next update which only picks from the available regions to that user.

**Comment by TheDon22** [comment]
thanks for the update. cheers

**Comment by tok-kkk** [comment]
Close this issue as it has been fixed in the latest master branch.
